In [ ]:
import numpy as np

math = np.array([1, 2, 3, 4, 5])
mt1 = math.astype(float) #função 'astype' usada para conversão de tipos de dados, no caso 'int' para 'float'

#criar arrays vazios tipificados
#empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("----------")
#matriz 4x3 com valores zero
zeros = np.zeros([4, 3])
print(zeros)
print("----------")
#com valores iguais a um
um = np.ones([2, 3])
print(um)
print("----------")
#matriz quadrada com diagonal principal com valores q e outros valores zero
diagonal = np.eye(3)
print(diagonal)

In [ ]:
#valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print("----------")
#valores aletórios distribuição normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print("----------")
#vaores aletórios 3 x 4
ale3 = (10*np.random.random((3, 4)))
print(ale3)
print("----------")
#outra forma de gerar aletórios
#uso de semente
gnr = np.random.default_rng(1)
ale4 = gnr.random(3)
print(ale4)
print("----------")
#gerar inteiros
ale5 = gnr.integers(10, size=(3, 4))
print(ale5)

In [5]:
#unique remove repetições
j = np.array([10, 10, 10, 11, 13, 14, 10, 17])
j = np.unique(j)
print(j)

[10 11 13 14 17]


In [8]:
#funções matemáticas
#adição e multiplicação de matriz
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 10], [1, 10]])

res1 = n+o
print(res1)
print("----------")
res2 = n*o #elemento a elemento
print(res2)

[[ 2 12]
 [ 4 14]]
----------
[[ 1 20]
 [ 3 40]]
